Issue #NUCIVIC-1956: Ahoy command to create subtheme from kit

diff --git a/.ahoy/theme.ahoy.yml b/.ahoy/theme.ahoy.yml
--- a/.ahoy/theme.ahoy.yml
+++ b/.ahoy/theme.ahoy.yml
@@ -50,3 +50,35 @@ commands:
     usage: 'compile and watch for changes'
     cmd: |
       ahoy cmd-proxy "cd dkan/themes/nuboot_radix \&\& gulp"
+
+
+  new-from-kit:
+    usage: 'creates a new theme based on nuboot-radix'
+    cmd: |
+      ARGS="{{args}}"
+      if [[ -z "$ARGS" ]]; then
+          echo "Please specify the name of the theme you want to create."
+          exit 1
+      fi
+      THEME_DIR="docroot/sites/all/themes/$ARGS"
+      if [[ -d "$THEME_DIR" ]]; then
+        echo "Theme $ARGS found at $THEME_DIR. Please remove it first"
+        exit 1;
+      else
+        echo "Creating theme $ARGS at $THEME_DIR"
+      fi
+      ORIGINAL_THEME=`ahoy drush vget theme_default --format=string`
+      ahoy drush vset theme_default radix
+      ahoy cmd-proxy drush cc drush
+      KIT_URL="https://github.com/NuCivic/radix-kit-nuboot/archive/master.zip"
+      if ahoy cmd-proxy wget -q "$KIT_URL"; then
+        ahoy cmd-proxy unzip master.zip
+        ahoy cmd-proxy rm -rf master.zip
+        ahoy cmd-proxy rm -rf dkan/themes/contrib/radix/kits/nuboot
+        ahoy cmd-proxy mv radix-kit-nuboot-master dkan/themes/contrib/radix/kits/nuboot
+        ahoy drush radix $ARGS --kit='nuboot'
+      else
+        echo "Can't seem to download kit from $KIT_URL, restoring original theme"
+        ahoy drush vset theme_default $ORIGINAL_THEME
+        exit 1;
+      fi
