Reset admin password after site install

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -11,7 +11,8 @@ references:
         mv ~/dkan .
         dktl make
         dktl drush site-install -y || true
-
+        dktl drush user-password admin --password=admin
+        
   install_tests: &install_tests
     run:
       name: Install tests
@@ -79,7 +80,8 @@ jobs:
           command: |
             export PATH=$PATH:~/dkan-tools/bin
             exit_status=0
-            (cd dkan/test; circleci tests glob features/*.feature | circleci tests split --split-by=filesize ) | while read file; do if ! dktl test:behat $file; then exit_status=$?; fi; done
+            (cd dkan/test; circleci tests glob features/*.feature | circleci tests split --split-by=filesize ) | while read file; do if ! dktl test:behat $file; then exit_status=1; echo "FAILED SCENARIO"; fi; done
+            echo "exit_status = $exit_status";
             exit $exit_status
 
 workflows:
